### ISSUE TITLE
How to use his interface connection the VPN

### ISSUE THREAD

**Issue by hackxhj** [KatekovAnton/iOS-OpenVPN-Sample#1]
Project to compile successfully
But I can't use it ，
How to use his interface connection the VPN
can you give a example  thank you

**Comment by KatekovAnton** [comment]
Hi. To make it work you should replace its work with /dev/tun with the iOS SDK way: 

`NEPacketTunnelFlow  readPacketsWithCompletionHandler ....`

get this packets and inject them to openvpn circle. 

then get packet from socket, decode them and inject back to flow:

`NEPacketTunnelFlow writePackets` 

with protocol 2

**Comment by hackxhj** [comment]
thank you .i give it a try

**Comment by rsimenok** [comment]
@hackxhj do you have any progress with implementing OpenVPN?)

**Comment by hackxhj** [comment]
@rsimenok no ,I found that implementation is a bit difficult for me So I gave up，But I know ios9 can do this

**Comment by Deepak050392** [comment]
I have a problem in implementing OpenVPN in IOS.. I don't know how to implement.

**Comment by yuguowen** [comment]
Do you solve the problem in implementing OpenVPN in iOS. Thank you !

**Comment by yuguowen** [comment]
Do you have any progress on openvpn research?

**Comment by Deepak050392** [comment]
I have no option.. Please help me.

**Comment by yuguowen** [comment]
@Deepak050392 I'm sorry, now I also in research openvpn, but have no effect...

**Comment by yuguowen** [comment]
@KatekovAnton   Glad to see your demo, but now I want to connect to their configuration of openvpn server, do you have what method?Thank you again!

**Comment by KatekovAnton** [comment]
@yuguowen sadly I cannot publish the code. Code provided in this repo is just a plain openvpn library + all its dependencies + project configured for xcode. To make it work you should replace its work with /dev/tun with the iOS SDK way: 

`NEPacketTunnelFlow  readPacketsWithCompletionHandler ....`

get this packets and inject them to openvpn circle. 

then get packet from socket, decode them and inject back to flow:

`NEPacketTunnelFlow writePackets` 

with protocol 2. You will need to implement your own main loop like in function

`static void tunnel_point_to_point (struct context *c)`

inside of openvpn.c, which is calling 

`void process_io (struct context *c)`

all main work is located there. To get access to network extensions refer this article https://developer.apple.com/reference/networkextension/netunnelprovidermanager

**Comment by yuguowen** [comment]
@KatekovAnton   Thank you. But I still don't know how to connect your own openvpn server.Could you give me to write a demo, and then sent to my mailbox?My email is gwgeek@163.com, thank you again

**Comment by yuguowen** [comment]
@KatekovAnton  Do you mean I can creat an ios app  that can connect my own openVPN server?Need to answer quickly. Thanks again.

**Comment by KatekovAnton** [comment]
@yuguowen yes you can connect to any vpn server

**Comment by yuguowen** [comment]
@KatekovAnton   Do you mean I can connect my own openvpn server and I don't use openvpnAPP official offer?
maybe you don't understand  me. I mean I want to create an APP and don't use any other APP,then I can connect my own openvpn server.Do you mean I can do it?If so,how can I do it?if so,can you give me a demo to connect my own vpn server.Thank you very much.

**Comment by KatekovAnton** [comment]
@yuguowen check your email
